### ISSUE TITLE
[BUG] Repo Issue

### ISSUE THREAD

**Issue by max21910** [userbradley/BeReal#72]
after running the command :  mkdocs serve
this is the output :
 ```
INFO    -  DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
           Material emoji logic has been officially moved into mkdocs-material
           version 9.4. Please use Material's
           'material.extensions.emoji.twemoji'
           instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

           ```
           markdown_extensions:
             - pymdownx.emoji:
                 emoji_index: !!python/name:material.extensions.emoji.twemoji
                 emoji_generator: !!python/name:material.extensions.emoji.to_svg
           ```

           'mkdocs_material_extensions' is deprecated and will no longer be
           supported moving forward. This is the last release.

             File
           "/opt/homebrew/lib/python3.11/site-packages/materialx/emoji.py", line
           118, in twemoji
               return _patch_index(options)
             File
           "/opt/homebrew/lib/python3.11/site-packages/materialx/emoji.py", line
           68, in _deprecated_func
               warnings.warn(
WARNING -  Material emoji logic has been officially moved into mkdocs-material
           version 9.4. Please use Material's
           'material.extensions.emoji.twemoji'
           instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

           ```
           markdown_extensions:
             - pymdownx.emoji:
                 emoji_index: !!python/name:material.extensions.emoji.twemoji
                 emoji_generator: !!python/name:material.extensions.emoji.to_svg
           ```

           'mkdocs_material_extensions' is deprecated and will no longer be
           supported moving forward. This is the last release.
INFO    -  Building documentation...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 277, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 527, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 138, in on_config
    self.font = self._load_font(config)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 454, in _load_font
    self._load_font_from_google(name)
  File "/opt/homebrew/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 477, in _load_font_from_google
    zip = ZipFile(tmp)
          ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1304, in __init__
    self._RealGetContents()
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipfile.py", line 1371, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
 ```
any ideas ??

**Comment by userbradley** [comment]
Ah yeah this affected my site too. If you do a the below it should work

```shell
pip3 install mkdocs-material=="9.5.17"
```

This got broken when google changed their API spec for the fonts

**Comment by userbradley** [comment]
@max21910 did you get it working?

**Comment by max21910** [comment]
Hi, sorry for the delay. After encountering some issues with my Mac, I've switched to Windows. However, I'm still facing the same problems even after following your suggestion. Here's the error message:
        ```
 WARNING -  Material emoji logic has been officially moved into mkdocs-material
           version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
           instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

          markdown_extensions:
             - pymdownx.emoji:
                 emoji_index: !!python/name:material.extensions.emoji.twemoji
                 emoji_generator: !!python/name:material.extensions.emoji.to_svg

           'mkdocs_material_extensions' is deprecated and will no longer be
           supported moving forward. This is the last release.
INFO    -  Building documentation...
ERROR   -  Required dependencies of "social" plugin not found:
           - ModuleNotFoundError("No module named 'cairosvg'")
           - ModuleNotFoundError("No module named 'PIL'")

           --> Install with: pip install "mkdocs-material[imaging]"

Aborted with a BuildError!
        ```

**Comment by userbradley** [comment]
@max21910  I have fixed it. Please approve https://github.com/userbradley/BeReal/pull/75 and then checkout main on your laptop and try running it, should be fixed

```shell
git checkout main && git reset --hard origin/main
```

**Comment by max21910** [comment]
It works thanks !
